spring:
# ------ 新增配置开始 ------
  servlet:
    multipart:
      max-file-size: 50MB      # 单个文件最大 50MB (按需调整)
      max-request-size: 50MB   # 整个请求最大 50MB
# ------ 新增配置结束 ------
#  链接数据库
  datasource:
    url: jdbc:mysql://localhost:3306（自己的端口）/simple_demo?（数据库名）useSSL=false&serverTimezone=UTC
    username:   # 写你的用户
    password:   # 写你的密码
#定义是否由其自动生成数据库！
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
#配置API

zhipu:
#  embedding模型都要钱
  embedding-model: "embedding-3"
#  花钱模型
#  chat-model: "glm-4-plus"
#  免费模型
  chat-model: "glm-4.5-flash"

upload:
  dir: .
  root: uploads/
  avatar: uploads/avatar/

  docs: uploads/docs/
